/*
 * DescuentosElcoView.java
 */

package descuentoselco;

import java.awt.event.ActionEvent;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import java.text.DecimalFormat;
import java.net.URL;

/**
 * The application's main frame.
 */
public class DescuentosElcoView extends FrameView {

    public DescuentosElcoView(SingleFrameApplication app) {
        super(app);

        initComponents();
        URL url = this.getClass().
                getResource("resources/Descuento.jpg");
        if(url != null){
            ImageIcon icono = new ImageIcon(url);
            this.getFrame().setIconImage(icono.getImage());
        }
        this.getFrame().setAlwaysOnTop(true);
        
        //Hace que el campoPrecio reciba el foco al iniciar la aplicación.
        this.getFrame().addWindowFocusListener(new WindowAdapter() {
            @Override
            public void windowGainedFocus(WindowEvent e) {
                campoPrecio.requestFocusInWindow();
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = DescuentosElcoApp.getApplication().getMainFrame();
            aboutBox = new DescuentosElcoAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        DescuentosElcoApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioBoton1 = new javax.swing.JRadioButton();
        radioBoton2 = new javax.swing.JRadioButton();
        radioBoton3 = new javax.swing.JRadioButton();
        radioBoton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        campoDto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoUds = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoDtoUds = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoFinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoPrecio = new javax.swing.JTextField();
        botonBorrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        etiIvaSeleccionado = new javax.swing.JLabel();
        campoIvaPersonalizado = new misClases.utilidades.swing.JTextFieldNumerosDecimales();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        ayudaMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(descuentoselco.DescuentosElcoApp.class).getContext().getResourceMap(DescuentosElcoView.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        buttonGroup1.add(radioBoton1);
        radioBoton1.setText(resourceMap.getString("radioBoton1.text")); // NOI18N
        radioBoton1.setActionCommand(resourceMap.getString("radioBoton1.actionCommand")); // NOI18N
        radioBoton1.setFocusable(false);
        radioBoton1.setName("radioBoton1"); // NOI18N
        radioBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBoton2);
        radioBoton2.setText(resourceMap.getString("radioBoton2.text")); // NOI18N
        radioBoton2.setActionCommand(resourceMap.getString("radioBoton2.actionCommand")); // NOI18N
        radioBoton2.setFocusable(false);
        radioBoton2.setName("radioBoton2"); // NOI18N
        radioBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBoton3);
        radioBoton3.setSelected(true);
        radioBoton3.setText(resourceMap.getString("radioBoton3.text")); // NOI18N
        radioBoton3.setActionCommand(resourceMap.getString("radioBoton3.actionCommand")); // NOI18N
        radioBoton3.setFocusable(false);
        radioBoton3.setName("radioBoton3"); // NOI18N
        radioBoton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBoton4);
        radioBoton4.setText(resourceMap.getString("radioBoton4.text")); // NOI18N
        radioBoton4.setActionCommand(resourceMap.getString("radioBoton4.actionCommand")); // NOI18N
        radioBoton4.setFocusable(false);
        radioBoton4.setName("radioBoton4"); // NOI18N
        radioBoton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoton4ActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        campoDto.setText(resourceMap.getString("campoDto.text")); // NOI18N
        campoDto.setName("campoDto"); // NOI18N
        campoDto.setNextFocusableComponent(campoUds);
        campoDto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanado(evt);
            }
        });
        campoDto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoDtoKeyPressed(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        campoUds.setText(resourceMap.getString("campoUds.text")); // NOI18N
        campoUds.setName("campoUds"); // NOI18N
        campoUds.setNextFocusableComponent(campoDtoUds);
        campoUds.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanado(evt);
            }
        });
        campoUds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoUdsKeyPressed(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        campoDtoUds.setText(resourceMap.getString("campoDtoUds.text")); // NOI18N
        campoDtoUds.setName("campoDtoUds"); // NOI18N
        campoDtoUds.setNextFocusableComponent(campoPrecio);
        campoDtoUds.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanado(evt);
            }
        });
        campoDtoUds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoDtoUdsKeyPressed(evt);
            }
        });

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        campoFinal.setBackground(resourceMap.getColor("campoFinal.background")); // NOI18N
        campoFinal.setEditable(false);
        campoFinal.setFont(resourceMap.getFont("campoFinal.font")); // NOI18N
        campoFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoFinal.setText(resourceMap.getString("campoFinal.text")); // NOI18N
        campoFinal.setFocusable(false);
        campoFinal.setName("campoFinal"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        campoPrecio.setText(resourceMap.getString("campoPrecio.text")); // NOI18N
        campoPrecio.setFocusCycleRoot(true);
        campoPrecio.setName("campoPrecio"); // NOI18N
        campoPrecio.setNextFocusableComponent(campoDto);
        campoPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanado(evt);
            }
        });
        campoPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoPrecioKeyPressed(evt);
            }
        });

        botonBorrar.setText(resourceMap.getString("botonBorrar.text")); // NOI18N
        botonBorrar.setToolTipText(resourceMap.getString("botonBorrar.toolTipText")); // NOI18N
        botonBorrar.setFocusable(false);
        botonBorrar.setName("botonBorrar"); // NOI18N
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        etiIvaSeleccionado.setFont(resourceMap.getFont("etiIvaSeleccionado.font")); // NOI18N
        etiIvaSeleccionado.setText(resourceMap.getString("etiIvaSeleccionado.text")); // NOI18N
        etiIvaSeleccionado.setName("etiIvaSeleccionado"); // NOI18N
        etiIvaSeleccionado.setOpaque(true);

        campoIvaPersonalizado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoIvaPersonalizado.setText(resourceMap.getString("campoIvaPersonalizado.text")); // NOI18N
        campoIvaPersonalizado.setName("campoIvaPersonalizado"); // NOI18N
        campoIvaPersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIvaPersonalizadoActionPerformed(evt);
            }
        });
        campoIvaPersonalizado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoIvaPersonalizadoFocusGained(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(campoDtoUds, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addGap(41, 41, 41))
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radioBoton3)
                                        .addComponent(radioBoton1)
                                        .addComponent(radioBoton2)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(campoIvaPersonalizado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radioBoton4, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addContainerGap(59, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                    .addComponent(campoUds, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addGap(41, 41, 41))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                    .addComponent(campoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addGap(41, 41, 41)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoDto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addGap(41, 41, 41))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(botonBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(etiIvaSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(radioBoton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBoton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(radioBoton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBoton4))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoIvaPersonalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoDto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoUds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoDtoUds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(etiIvaSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(descuentoselco.DescuentosElcoApp.class).getContext().getActionMap(DescuentosElcoView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setToolTipText(resourceMap.getString("exitMenuItem.toolTipText")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        ayudaMenuItem.setText(resourceMap.getString("ayudaMenuItem.text")); // NOI18N
        ayudaMenuItem.setToolTipText(resourceMap.getString("ayudaMenuItem.toolTipText")); // NOI18N
        ayudaMenuItem.setName("ayudaMenuItem"); // NOI18N
        ayudaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(ayudaMenuItem);

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setToolTipText(resourceMap.getString("aboutMenuItem.toolTipText")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void radioBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoton1ActionPerformed
        this.obtenerIvaBoton(evt);
    }//GEN-LAST:event_radioBoton1ActionPerformed

    private void radioBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoton2ActionPerformed
        this.obtenerIvaBoton(evt);
    }//GEN-LAST:event_radioBoton2ActionPerformed

    private void radioBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoton3ActionPerformed
       this.obtenerIvaBoton(evt);
    }//GEN-LAST:event_radioBoton3ActionPerformed

    private void radioBoton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoton4ActionPerformed
        this.obtenerIvaBoton(evt);
    }//GEN-LAST:event_radioBoton4ActionPerformed

    private void obtenerIvaBoton(ActionEvent evt){
        try{
            this.iva = Double.parseDouble(evt.getActionCommand());
        }
        catch(NumberFormatException ex){
            this.iva = Double.parseDouble(evt.getActionCommand());
            //this.ivaEnBoton = Double.parseDouble(evt.getActionCommand());
            this.actualizarEtiquetaIvaSeleccionado();
            this.calcularPrecioFinal();
            return;
        }
        this.iva = Double.parseDouble(this.campoIvaPersonalizado.getText());
        this.campoIvaPersonalizado.reiniciarVariableBoolean();
        this.actualizarEtiquetaIvaSeleccionado();
        this.calcularPrecioFinal();
    }
    private void campoPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPrecioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER ||
                evt.getKeyCode() == KeyEvent.VK_DOWN){
            this.calcularPrecioFinal();
            this.campoDto.requestFocus();
        }
        else if(evt.getKeyCode() == KeyEvent.VK_UP){
            this.calcularPrecioFinal();
            this.campoDtoUds.requestFocus();
        }
    }//GEN-LAST:event_campoPrecioKeyPressed

    private void campoDtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDtoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER ||
                evt.getKeyCode() == KeyEvent.VK_DOWN){
            this.calcularPrecioFinal();
            this.campoUds.requestFocus();
        }
        else if(evt.getKeyCode() == KeyEvent.VK_UP){
            this.calcularPrecioFinal();
            this.campoPrecio.requestFocus();
        }
    }//GEN-LAST:event_campoDtoKeyPressed

    private void campoUdsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUdsKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER ||
                evt.getKeyCode() == KeyEvent.VK_DOWN){
            this.calcularPrecioFinal();
            this.campoDtoUds.requestFocus();
        }
        else if(evt.getKeyCode() == KeyEvent.VK_UP){
            this.calcularPrecioFinal();
            this.campoDto.requestFocus();
        }
    }//GEN-LAST:event_campoUdsKeyPressed

    private void campoDtoUdsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDtoUdsKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER ||
                evt.getKeyCode() == KeyEvent.VK_DOWN){
            this.calcularPrecioFinal();
            this.campoPrecio.requestFocus();
        }
        else if(evt.getKeyCode() == KeyEvent.VK_UP){
            this.calcularPrecioFinal();
            this.campoUds.requestFocus();
        }
    }//GEN-LAST:event_campoDtoUdsKeyPressed

    private void campoFocoGanado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFocoGanado
        JTextField campo = (JTextField)evt.getSource();
        campo.selectAll();
    }//GEN-LAST:event_campoFocoGanado

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        if(evt == null);
        this.campoPrecio.setText("0.0");
        this.campoDto.setText("0.0");
        this.campoUds.setText("0");
        this.campoDtoUds.setText("0");
        this.campoFinal.setText("0,00");
        this.campoPrecio.requestFocusInWindow();
        this.campoPrecio.selectAll();
}//GEN-LAST:event_botonBorrarActionPerformed

    private void ayudaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaMenuItemActionPerformed
        if(evt == null);
        String mensaje = "Para aplicar descuentos en cadena\n" +
                "escríbalos separados por la barra \' / \'\n" +
                "de esta forma: 10.5/5.32/1.37";
        JOptionPane.showMessageDialog(this.getFrame(),
                mensaje, "Ayuda", JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_ayudaMenuItemActionPerformed

    private void campoIvaPersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIvaPersonalizadoActionPerformed
        this.obtenerIvaBoton(evt);
        
    }//GEN-LAST:event_campoIvaPersonalizadoActionPerformed

    private void campoIvaPersonalizadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoIvaPersonalizadoFocusGained
        if(evt == null);
        this.campoIvaPersonalizado.selectAll();
    }//GEN-LAST:event_campoIvaPersonalizadoFocusGained

    private void calcularPrecioFinal(){
        //this.actualizarEtiquetaIvaSeleccionado();
        // obtenemos el precio inicial
        try{
            this.precioInicial =
                    Double.parseDouble(this.campoPrecio.getText());
        }
        catch(NumberFormatException ex){
            this.campoPrecio.setText("0.0");
            this.precioInicial = 0.0d;
        }
        // si el precio inicial es cero salimos del método
        if(this.precioInicial == 0.0) return;

        this.precioTotal = this.precioInicial;


        // obtenemos los descuentos
        double[] descuentos = this.getDescuentos();
        if(descuentos == null){
            this.campoDto.setText("0.0");
        }

        // obtenemos las unidades
        try{
            this.uds = Integer.parseInt(this.campoUds.getText());
        }
        catch(NumberFormatException ex){
            this.campoUds.setText("0");
            this.uds = 0;
        }

        // obtenemos las unidades de descuento
        try{
            this.dtoUds = Integer.parseInt(this.campoDtoUds.getText());
        }
        catch(NumberFormatException ex){
            this.campoDtoUds.setText("0");
            this.dtoUds = 0;
        }

        // hacemos los cálculos
        if(descuentos != null && descuentos.length > 0){
            for(int i = 0; i < descuentos.length; i++){
                this.precioTotal =
                        this.precioTotal -
                        (this.precioTotal * descuentos[i] / 100);
            }
        }
        
        if(this.uds != 0 && this.dtoUds != 0){
            this.precioTotal =
                    this.precioTotal * this.uds / (this.uds + this.dtoUds);
        }

        // aplicamos el IVA.
        this.precioTotal = this.precioTotal * (1 + this.iva / 100);
       
        // presentamos el resultado en el campo 'Precio Final'
        this.campoFinal.setText(this.formato.format(this.precioTotal));
    }

    private double[] getDescuentos(){
        String[] tokens = this.campoDto.getText().split("/");
        if(tokens.length == 0) return null;
        double[] descuentos = new double[tokens.length];
        for(int i = 0; i < tokens.length; i++){
            try{
                descuentos[i] = Double.parseDouble(tokens[i]);
            }
            catch(NumberFormatException ex){
                descuentos = null;
                break;
            }
        }
        return descuentos;
    }

    private void actualizarEtiquetaIvaSeleccionado(){
        DecimalFormat f = new DecimalFormat("####.####");
        this.etiIvaSeleccionado.setText("IVA: " +f.format(this.iva) + " %");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ayudaMenuItem;
    private javax.swing.JButton botonBorrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoDto;
    private javax.swing.JTextField campoDtoUds;
    private javax.swing.JTextField campoFinal;
    private misClases.utilidades.swing.JTextFieldNumerosDecimales campoIvaPersonalizado;
    private javax.swing.JTextField campoPrecio;
    private javax.swing.JTextField campoUds;
    private javax.swing.JLabel etiIvaSeleccionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JRadioButton radioBoton1;
    private javax.swing.JRadioButton radioBoton2;
    private javax.swing.JRadioButton radioBoton3;
    private javax.swing.JRadioButton radioBoton4;
    // End of variables declaration//GEN-END:variables


    private JDialog aboutBox;
    private double iva = 21.0d;
    private double precioInicial = 0.0d;
    //private double dto = 0.0d;
    private int dtoUds = 0;
    private int uds = 0;
    private double precioTotal = 0.0d;
    private final DecimalFormat formato = new DecimalFormat("###,##0.00#");
}
